name: Sync labels
on:
  push:
    paths: 
    - './labels.yml'
  workflow_dispatch:
   
jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: EndBug/label-sync@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config-file: ./labels.yaml
